import  { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/providers/AuthProvider";
import { Footer } from '@/components/layout/footer';
import { Header } from "@/components/layout/header";
import { getServerSession } from "next-auth";

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Onomato, baby",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession();
    console.log(session);
    return (
        <html lang="en">
            <body className="bg-grisBackground m-0">
				<AuthProvider>
                    <Header />
					    {children}
                    <Footer />
				</AuthProvider>
			</body>
        </html>
    );
}
