/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    'page-images': PageImage;
    tags: Tag;
    authors: Author;
    books: Book;
    'book-files': BookFile;
    'book-pages': BookPage;
    'book-votes': BookVote;
    'followed-authors': FollowedAuthor;
    'followed-books': FollowedBook;
    orders: Order;
    payments: Payment;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    tags: {
      books: 'books';
    };
    authors: {
      books: 'books';
      credited: 'books';
      followers: 'followed-authors';
    };
    books: {
      pages: 'book-pages';
      followers: 'followed-books';
      votes: 'book-votes';
    };
    orders: {
      payment: 'payments';
    };
    users: {
      author: 'authors';
      orders: 'orders';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    'page-images': PageImagesSelect<false> | PageImagesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    'book-files': BookFilesSelect<false> | BookFilesSelect<true>;
    'book-pages': BookPagesSelect<false> | BookPagesSelect<true>;
    'book-votes': BookVotesSelect<false> | BookVotesSelect<true>;
    'followed-authors': FollowedAuthorsSelect<false> | FollowedAuthorsSelect<true>;
    'followed-books': FollowedBooksSelect<false> | FollowedBooksSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payment-settings': PaymentSetting;
  };
  globalsSelect: {
    'payment-settings': PaymentSettingsSelect<false> | PaymentSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      extractBookPages: TaskExtractBookPages;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-images".
 */
export interface PageImage {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  books?: {
    docs?: (number | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in cents (e.g. 80000 = $800).
   */
  price?: number | null;
  lastFreePage?: number | null;
  slug?: string | null;
  credits?:
    | {
        author: number | Author;
        role?: ('autor completo' | 'guionista' | 'dibujante' | 'entintador' | 'colorista' | 'letrista') | null;
        id?: string | null;
      }[]
    | null;
  owner: number | Author;
  cover?: (number | null) | Media;
  pdf?: (number | null) | BookFile;
  tags?: (number | Tag)[] | null;
  pages?: {
    docs?: (number | BookPage)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  followers?: {
    docs?: (number | FollowedBook)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  votes?: {
    docs?: (number | BookVote)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name?: string | null;
  slug?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  user: number | User;
  profilePhoto?: (number | null) | Media;
  headerPhoto?: (number | null) | Media;
  socialmedias?:
    | {
        type?: ('twitter' | 'instagram' | 'facebook' | 'youtube' | 'tiktok' | 'website') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  payoutAccounts?:
    | {
        provider: 'mercadopago' | 'paypal';
        accountId: string;
        id?: string | null;
      }[]
    | null;
  books?: {
    docs?: (number | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  credited?: {
    docs?: (number | Book)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  followers?: {
    docs?: (number | FollowedAuthor)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'editor' | 'author' | 'reader')[] | null;
  author?: {
    docs?: (number | Author)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  status?: ('pending' | 'paid' | 'cancelled' | 'refunded') | null;
  user: number | User;
  book: number | Book;
  /**
   * Total charged, in cents.
   */
  grossAmount?: number | null;
  /**
   * Platform commission, in cents.
   */
  platformFee?: number | null;
  /**
   * Paid directly to the book owner, in cents.
   */
  authorAmount?: number | null;
  currencyId?: string | null;
  provider?: ('mercadopago' | 'paypal') | null;
  providerReference?: string | null;
  payment?: {
    docs?: (number | Payment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  order: number | Order;
  provider: 'mercadopago' | 'paypal';
  providerPaymentId?: string | null;
  /**
   * Amount, in cents.
   */
  amount?: number | null;
  currencyId?: string | null;
  status: 'approved' | 'pending' | 'rejected' | 'refunded';
  date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "followed-authors".
 */
export interface FollowedAuthor {
  id: number;
  user: number | User;
  author: number | Author;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-files".
 */
export interface BookFile {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-pages".
 */
export interface BookPage {
  id: number;
  pageNumber?: number | null;
  book: number | Book;
  image?: (number | null) | PageImage;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "followed-books".
 */
export interface FollowedBook {
  id: number;
  user: number | User;
  book: number | Book;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-votes".
 */
export interface BookVote {
  id: number;
  user: number | User;
  book: number | Book;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title?: string | null;
  slug?: string | null;
  layout?:
    | (
        | {
            slides?:
              | {
                  title?: {
                    tag?: ('h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6') | null;
                    text?: string | null;
                  };
                  description?: string | null;
                  /**
                   * Desktop background (recommended 1920x1080)
                   */
                  backgroundImage?: (number | null) | Media;
                  /**
                   * Falls back to the desktop image if empty
                   */
                  mobileBackgroundImage?: (number | null) | Media;
                  /**
                   * 0 = transparent, 100 = fully opaque
                   */
                  backgroundOverlayOpacity?: number | null;
                  primaryButton?: {
                    label?: string | null;
                    url?: string | null;
                    newTab?: boolean | null;
                  };
                  secondaryButton?: {
                    label?: string | null;
                    url?: string | null;
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroV2';
          }
        | {
            heading?: {
              tag?: ('h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6') | null;
              text?: string | null;
            };
            /**
             * Displays above the main heading
             */
            subheading?: string | null;
            description?: string | null;
            viewAllButton?: {
              label?: string | null;
              url?: string | null;
              newTab?: boolean | null;
            };
            sliderHeading?: string | null;
            backgroundVisual?: (number | null) | Media;
            backgroundVisualMobile?: (number | null) | Media;
            brandSvg?: (number | null) | Media;
            /**
             * How many cards to display
             */
            productsToShow?: number | null;
            /**
             * On = auto-pick by criteria; off = choose manually
             */
            automaticSelection?: boolean | null;
            selectedBooks?: (number | Book)[] | null;
            selectionType?: ('new_releases' | 'trending_now' | 'best_sellers') | null;
            /**
             * Position when multiple reels are stacked
             */
            blockPosition?: ('default' | 'first' | 'last') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productReel';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'extractBookPages';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'extractBookPages') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'page-images';
        value: number | PageImage;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'book-files';
        value: number | BookFile;
      } | null)
    | ({
        relationTo: 'book-pages';
        value: number | BookPage;
      } | null)
    | ({
        relationTo: 'book-votes';
        value: number | BookVote;
      } | null)
    | ({
        relationTo: 'followed-authors';
        value: number | FollowedAuthor;
      } | null)
    | ({
        relationTo: 'followed-books';
        value: number | FollowedBook;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-images_select".
 */
export interface PageImagesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  books?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  user?: T;
  profilePhoto?: T;
  headerPhoto?: T;
  socialmedias?:
    | T
    | {
        type?: T;
        url?: T;
        id?: T;
      };
  payoutAccounts?:
    | T
    | {
        provider?: T;
        accountId?: T;
        id?: T;
      };
  books?: T;
  credited?: T;
  followers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  price?: T;
  lastFreePage?: T;
  slug?: T;
  credits?:
    | T
    | {
        author?: T;
        role?: T;
        id?: T;
      };
  owner?: T;
  cover?: T;
  pdf?: T;
  tags?: T;
  pages?: T;
  followers?: T;
  votes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-files_select".
 */
export interface BookFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-pages_select".
 */
export interface BookPagesSelect<T extends boolean = true> {
  pageNumber?: T;
  book?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-votes_select".
 */
export interface BookVotesSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "followed-authors_select".
 */
export interface FollowedAuthorsSelect<T extends boolean = true> {
  user?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "followed-books_select".
 */
export interface FollowedBooksSelect<T extends boolean = true> {
  user?: T;
  book?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  status?: T;
  user?: T;
  book?: T;
  grossAmount?: T;
  platformFee?: T;
  authorAmount?: T;
  currencyId?: T;
  provider?: T;
  providerReference?: T;
  payment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  order?: T;
  provider?: T;
  providerPaymentId?: T;
  amount?: T;
  currencyId?: T;
  status?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroV2?:
          | T
          | {
              slides?:
                | T
                | {
                    title?:
                      | T
                      | {
                          tag?: T;
                          text?: T;
                        };
                    description?: T;
                    backgroundImage?: T;
                    mobileBackgroundImage?: T;
                    backgroundOverlayOpacity?: T;
                    primaryButton?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                        };
                    secondaryButton?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productReel?:
          | T
          | {
              heading?:
                | T
                | {
                    tag?: T;
                    text?: T;
                  };
              subheading?: T;
              description?: T;
              viewAllButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              sliderHeading?: T;
              backgroundVisual?: T;
              backgroundVisualMobile?: T;
              brandSvg?: T;
              productsToShow?: T;
              automaticSelection?: T;
              selectedBooks?: T;
              selectionType?: T;
              blockPosition?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  author?: T;
  orders?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings".
 */
export interface PaymentSetting {
  id: number;
  /**
   * Platform commission taken from each sale (percent).
   */
  commissionPercent: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings_select".
 */
export interface PaymentSettingsSelect<T extends boolean = true> {
  commissionPercent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExtractBookPages".
 */
export interface TaskExtractBookPages {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}